version: "3.7"
services:
  webapp:
    build:
      context: .
      dockerfile: webmvc.Dockerfile
      args:
        buildno: 1
    expose:
      - "5000:80"
    environment:
      - VIRTUAL_HOST:pre.test.web.claimdi360.tk
      - LETSENCRYPT_HOST:pre.test.web.claimdi360.tk
      - LETSENCRYPT_EMAIL:panupong@anywheretogo.com