version: "3.7"
services:
  webapp:
    build:
      context: .
      dockerfile: webmvc.Dockerfile
      args:
        buildno: 1
    networks:
      - reverse-proxy
      - back
    expose:
      - 80
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - VIRTUAL_PORT=1234
      - VIRTUAL_HOST=pre.test.web.claimdi360.tk
      - LETSENCRYPT_HOST=pre.test.web.claimdi360.tk
      - LETSENCRYPT_EMAIL=panupong@anywheretogo.com
networks:
  reverse-proxy:
    external:
      name: reverse-proxy
  back:
    driver: bridge